location: "East US"
managed-environment-name: "momosuke-container-env"
dapr-app-port: 3000
dapr-app-protocol: "http"
dapr-enabled: false
ingress-external: true
ingress-target-port: 80
ingress-custom-domains-json: []
ingress-traffic-json:
  - label: production
    revisionName: yuhattor-container3--qpxyrnn
    weight: 100
scale-max-replicas: 5
scale-min-replicas: 1
scale-rules-json:
  - name: httpscalingrule
    custom:
      type: http
      metadata:
        concurrentRequests: "50"